dependencies:
  - python=3
  - pip:
    - spacy
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - tqdm
    - pillow
    - xlrd==1.2.0
    - vega_datasets
    - seaborn
