dependencies:
  - python=3
  - pip:
    - spacy
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - thinc
    - seaborn
    - tqdm
    - sklearn
    - pillow
    - xgboost
    - requests
    - lightgbm
    - catboost
    - pyproj
    - scrapy
    - pyecharts
    - bokeh
    - altair
    - geopandas
    - jupyter_contrib_nbextensions
    - tensorflow
    - opencv-python
    - ggplot
    - folium
    - fiona
    - cutecharts
    - plotly
    - xlrd
    - torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
