dependencies:
  - python=3
  - pip:
    - spacy
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - thinc
    - seaborn
    - tqdm
    - sklearn
    - pillow
    - requests
    - scrapy
    - pyecharts
    - bokeh
    - altair
    - jupyter_contrib_nbextensions
    - ggplot
    - folium
    - fiona
    - cutecharts
    - plotly
    - xlrd==1.2.0
    - vega_datasets
    - dash
    - bs4
